/*
*    ABL (3Dtouch) related changes
*/
#define ASSISTED_TRAMMING
#define TRAMMING_SCREW_THREAD 40
#define SHORT_MANUAL_Z_MOVE 0.005
#define PROBE_OFFSET_WIZARD
#define BABYSTEP_MULTIPLICATOR_Z  4
#define BABYSTEP_ZPROBE_OFFSET
#define BABYSTEP_ZPROBE_GFX_OVERLAY
#define BLTOUCH_DELAY 500
#define BLTOUCH_SET_5V_MODE

/*
*    General settings suggested by reddit thread
*/
#define HOTEND_IDLE_TIMEOUT
#define HOTEND_IDLE_TIMEOUT_SEC (8*60)
#define SLOWDOWN_DIVISOR 8
#define SHOW_REMAINING_TIME
#define USE_M73_REMAINING_TIME
#define ROTATE_PROGRESS_DISPLAY
#define PRINT_PROGRESS_SHOW_DECIMALS
#define STATUS_HEAT_PERCENT
#define E0_CURRENT      650
#define CANCEL_OBJECTS